apiVersion: v1
kind: PersistentVolume
metadata:
  name: mi-pv-nfs
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 192.168.1.24
    path: /root/data/
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mi-pvc-nfs
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
